ask_question:
  name: Ask Question
  description: >-
    Send a question to the AI model and receive a detailed response.
    The response will be stored in the conversation history and can be retrieved later.
    Response time may vary based on model selection and server load.
    Supports various AI models with different capabilities and pricing.
  fields:
    question:
      name: Question
      description: >-
        Your question or prompt for the AI assistant. Be specific and clear for better results.
        You can ask about home automation, technical advice, or general questions.
        For complex queries, consider breaking them into smaller parts.
        The system will maintain conversation context for follow-up questions.
      required: true
      example: |
        What automations would you recommend for a smart kitchen?
        Consider energy efficiency, convenience, and integration with:
        - Smart lighting
        - Appliance control
        - Temperature monitoring
        - Voice commands
      selector:
        text:
          multiline: true
          type: text

    model:
      name: Model
      description: >-
        Select an AI model to use (optional, overrides default setting).
        Different models have different capabilities, context limits, and response characteristics:
        - GPT-3.5 Turbo: Fast, efficient, good for most tasks
        - GPT-4: More capable, better reasoning, slower
        - Claude-3: Advanced capabilities, longer context
        Note: More capable models may have longer response times and higher API costs.
      required: false
      example: "gpt-3.5-turbo"
      default: "gpt-3.5-turbo"
      selector:
        select:
          custom_value: true
          options:
            - label: "GPT-3.5 Turbo (Fast & Efficient)"
              value: "gpt-3.5-turbo"
            - label: "GPT-3.5 Turbo 16K (Extended)"
              value: "gpt-3.5-turbo-16k"
            - label: "GPT-4 (Most Capable)"
              value: "gpt-4"
            - label: "GPT-4 32K (Extended Context)"
              value: "gpt-4-32k"
            - label: "GPT-4 Turbo (Latest)"
              value: "gpt-4-1106-preview"
            - label: "Claude-3 Sonnet (Balanced)"
              value: "claude-3-sonnet"
            - label: "Claude-3 Opus (Most Advanced)"
              value: "claude-3-opus"
          mode: dropdown

    temperature:
      name: Temperature
      description: >-
        Controls response creativity (0.0-2.0):
        0.0-0.3: Focused, consistent responses (best for technical/factual queries)
        0.4-0.7: Balanced responses (recommended for most uses)
        0.8-2.0: More creative, varied responses (best for brainstorming)
        Note: Higher values may produce less predictable results.
      required: false
      default: 0.7
      selector:
        number:
          min: 0.0
          max: 2.0
          step: 0.1
          mode: slider
          unit_of_measurement: ""

    max_tokens:
      name: Max Tokens
      description: >-
        Maximum length of the response (1-4096 tokens).
        Recommended ranges:
        - Short (256-512): Quick answers, status updates
        - Medium (512-1024): Detailed explanations
        - Long (1024-4096): Complex analysis
        Note: Token limits vary by model. Actual length may be shorter.
      required: false
      default: 1000
      selector:
        number:
          min: 1
          max: 4096
          step: 1
          mode: box

    system_prompt:
      name: System Prompt
      description: >-
        Optional system prompt to set context for this specific question.
        This will temporarily override the default system prompt.
        Use this to specify expertise areas, response format, or special instructions.
      required: false
      example: "You are a home automation expert focused on energy efficiency and security"
      selector:
        text:
          multiline: true

clear_history:
  name: Clear History
  description: >-
    Delete all stored questions and responses from the conversation history.
    This action cannot be undone. Consider using 'get_history' first if you need to backup the data.
    System prompt settings and configuration will be preserved.
  fields: {}

get_history:
  name: Get History
  description: >-
    Retrieve recent conversation history, including:
    - Questions and responses
    - Timestamps and response times
    - Models used and token counts
    - Temperature and other settings
    Results are ordered from newest to oldest.
  fields:
    limit:
      name: Limit
      description: >-
        Number of most recent conversations to return (1-100).
        Higher values return more history but may take longer to process.
        Default: 10 conversations
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: box

    filter_model:
      name: Filter by Model
      description: >-
        Only return conversations using a specific AI model.
        Leave empty to show all models.
      required: false
      selector:
        select:
          custom_value: true
          options:
            - label: "All Models"
              value: ""
            - label: "GPT-3.5 Turbo"
              value: "gpt-3.5-turbo"
            - label: "GPT-4"
              value: "gpt-4"
            - label: "GPT-4 Turbo"
              value: "gpt-4-1106-preview"
            - label: "Claude-3 Sonnet"
              value: "claude-3-sonnet"
            - label: "Claude-3 Opus"
              value: "claude-3-opus"
          mode: dropdown

    start_date:
      name: Start Date
      description: >-
        Optional start date for filtering history.
        Format: YYYY-MM-DD
      required: false
      selector:
        datetime:
          type: date

set_system_prompt:
  name: Set System Prompt
  description: >-
    Set default system behavior instructions for all future conversations.
    This defines how the AI should behave and respond to questions.
    The prompt will be used for all models unless overridden per question.
  fields:
    prompt:
      name: System Prompt
      description: >-
        Instructions that define how the AI should behave and respond.
        Be specific about:
        - Desired expertise and knowledge areas
        - Response tone and style
        - Output format preferences
        - Special handling instructions
        Maximum length: 1000 characters
      required: true
      example: |
        You are a home automation expert assistant. Focus on:
        1. Practical and efficient solutions
        2. Energy-saving recommendations
        3. Integration with popular smart home platforms
        4. Security and privacy considerations
        Provide detailed but concise responses with clear steps when applicable.
        Format complex responses with bullet points or numbered lists.
        Include warnings about potential risks or limitations.
      selector:
        text:
          multiline: true
