text_ai_call:
  name: Text AI Call
  description: Make a request to the Text AI service
  fields:
    prompt:
      name: Prompt
      description: The prompt to send to the AI service
      required: true
      example: "Tell me a joke about the weather"
      selector:
        text:
          multiline: true
    response_id:
      name: Response ID
      description: Unique identifier for the response Text Helper
      required: false
      default: "default"
      example: "weather_joke"
      selector:
        text:
    model:
      name: Model
      description: The AI model to use
      required: false
      default: "gpt-3.5-turbo"
      example: "gpt-4"
      selector:
        text:
    temperature:
      name: Temperature
      description: Sampling temperature (0-2)
      required: false
      default: 0.7
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
    max_tokens:
      name: Max Tokens
      description: Maximum number of tokens in the response
      required: false
      default: 150
      selector:
        number:
          min: 1
          max: 4096
    top_p:
      name: Top P
      description: Nucleus sampling parameter
      required: false
      default: 1.0
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    frequency_penalty:
      name: Frequency Penalty
      description: Frequency penalty parameter (-2.0 to 2.0)
      required: false
      default: 0.0
      selector:
        number:
          min: -2.0
          max: 2.0
          step: 0.1
    presence_penalty:
      name: Presence Penalty
      description: Presence penalty parameter (-2.0 to 2.0)
      required: false
      default: 0.0
      selector:
        number:
          min: -2.0
          max: 2.0
          step: 0.1
